/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlsmp.FunctionalInterface;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Locale;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author My Laptop
 */
public class BarChart extends javax.swing.JPanel {

    private DefaultCategoryDataset dataset;
    private JFreeChart chart;
    private CategoryPlot categoryPlot;
    private ChartPanel chartPanel;
//    
    /**
     * Creates new form BarChart
     */
    public BarChart() {
        initComponents();
        ShowBarChart();
    }

    public void ShowBarChart() {
        dataset = new DefaultCategoryDataset();

        dataset.addValue(200, "Chi phí", "Tháng 1");
        dataset.addValue(220, "Chi phí", "Tháng 2");
        dataset.addValue(300, "Chi phí", "Tháng 3");
        dataset.addValue(500,"Chi phí","Tháng 4");
        dataset.addValue(600,"Chi phí","Tháng 5");
        dataset.addValue(220,"Chi phí","Tháng 6");
        dataset.addValue(200,"Chi phí","Tháng 7");
        dataset.addValue(100,"Chi phí","Tháng 8");
        dataset.addValue(120,"Chi phí","Tháng 9");
        dataset.addValue(230,"Chi phí","Tháng 10");
        dataset.addValue(400,"Chi phí","Tháng 11");
        dataset.addValue(120,"Chi phí","Tháng 12");

        dataset.addValue(240, "Doanh thu", "Tháng 1");
        dataset.addValue(280, "Doanh thu", "Tháng 2");
        dataset.addValue(350, "Doanh thu", "Tháng 3");
        dataset.addValue(570 ,"Doanh thu","Tháng 4");
        dataset.addValue(660 ,"Doanh thu","Tháng 5");
        dataset.addValue(280 ,"Doanh thu","Tháng 6");
        dataset.addValue(270 ,"Doanh thu","Tháng 7");
        dataset.addValue(150 ,"Doanh thu","Tháng 8");
        dataset.addValue(190 ,"Doanh thu","Tháng 9");
        dataset.addValue(300 ,"Doanh thu","Tháng 10");
        dataset.addValue(480 ,"Doanh thu","Tháng 11");
        dataset.addValue(190 ,"Doanh thu","Tháng 12");

        dataset.addValue(40, "Lợi nhuận", "Tháng 1");
        dataset.addValue(70, "Lợi nhuận", "Tháng 2");
        dataset.addValue(50, "Lợi nhuận", "Tháng 3");
        dataset.addValue(70 ,"Lợi nhuận","Tháng 4");
        dataset.addValue(60 ,"Lợi nhuận","Tháng 5");
        dataset.addValue(60 ,"Lợi nhuận","Tháng 6");
        dataset.addValue(70 ,"Lợi nhuận","Tháng 7");
        dataset.addValue(50 ,"Lợi nhuận","Tháng 8");
        dataset.addValue(70 ,"Lợi nhuận","Tháng 9");
        dataset.addValue(70 ,"Lợi nhuận","Tháng 10");
        dataset.addValue(80 ,"Lợi nhuận","Tháng 11");
        dataset.addValue(70 ,"Lợi nhuận","Tháng 12");

        // creat chart
        chart = ChartFactory.createBarChart3D("Biểu đồ doanh thu Shop Mỹ Phẩm năm 2022", "", "triệu VND", dataset, PlotOrientation.VERTICAL, true, true, false);

        //categoryPlot = chart.getCategoryPlot();
        //

        //categoryPlot.setBackgroundPaint(Color.black);
        chartPanel = new ChartPanel(chart);
        chartPanel.setMouseWheelEnabled(true);

       // jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.setPreferredSize(new Dimension(1094, 449));
        jPanel1.add(chartPanel, BorderLayout.CENTER);
        repaint();
        //jPanel1.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
