//HOÀN THÀNH
package qlsmp.FunctionalInterface;

import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import qlsmp.DAO.KhoDAO;
import qlsmp.Model.SanPham;

/**
 *
 * @author My Laptop
 */
public class QLKho extends javax.swing.JFrame implements Runnable {
    
    List<SanPham> list = new ArrayList<>();
    public int page = 1;
    KhoDAO dao = new KhoDAO();

    /**
     * Creates new form QLKho
     */
    public QLKho() {
        initComponents();
        init();
    }
    
    void init() {
        setLocationRelativeTo(null);
        setTitle("Quản lý kho");
        this.getContentPane().setBackground(Color.WHITE);
        this.FillPageSP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnel6 = new javax.swing.JPanel();
        hinh6 = new javax.swing.JLabel();
        ten6 = new javax.swing.JLabel();
        lblgia6 = new javax.swing.JLabel();
        gia6 = new javax.swing.JLabel();
        sl6 = new javax.swing.JLabel();
        lblKho6 = new javax.swing.JLabel();
        pnel8 = new javax.swing.JPanel();
        hinh8 = new javax.swing.JLabel();
        ten8 = new javax.swing.JLabel();
        lblgia8 = new javax.swing.JLabel();
        gia8 = new javax.swing.JLabel();
        sl8 = new javax.swing.JLabel();
        lblKho8 = new javax.swing.JLabel();
        pnel5 = new javax.swing.JPanel();
        hinh5 = new javax.swing.JLabel();
        ten5 = new javax.swing.JLabel();
        lblgia5 = new javax.swing.JLabel();
        gia5 = new javax.swing.JLabel();
        sl5 = new javax.swing.JLabel();
        lblKho5 = new javax.swing.JLabel();
        pnel9 = new javax.swing.JPanel();
        hinh9 = new javax.swing.JLabel();
        ten9 = new javax.swing.JLabel();
        lblgia9 = new javax.swing.JLabel();
        gia9 = new javax.swing.JLabel();
        sl9 = new javax.swing.JLabel();
        lblKho9 = new javax.swing.JLabel();
        pnel12 = new javax.swing.JPanel();
        hinh12 = new javax.swing.JLabel();
        ten12 = new javax.swing.JLabel();
        lblgia12 = new javax.swing.JLabel();
        gia12 = new javax.swing.JLabel();
        sl12 = new javax.swing.JLabel();
        lblKho12 = new javax.swing.JLabel();
        pnel3 = new javax.swing.JPanel();
        hinh3 = new javax.swing.JLabel();
        ten3 = new javax.swing.JLabel();
        lblgia3 = new javax.swing.JLabel();
        gia3 = new javax.swing.JLabel();
        sl3 = new javax.swing.JLabel();
        lblKho3 = new javax.swing.JLabel();
        pnel7 = new javax.swing.JPanel();
        hinh7 = new javax.swing.JLabel();
        ten7 = new javax.swing.JLabel();
        lblgia7 = new javax.swing.JLabel();
        gia7 = new javax.swing.JLabel();
        sl7 = new javax.swing.JLabel();
        lblKho7 = new javax.swing.JLabel();
        pnel10 = new javax.swing.JPanel();
        hinh10 = new javax.swing.JLabel();
        ten10 = new javax.swing.JLabel();
        lblgia10 = new javax.swing.JLabel();
        gia10 = new javax.swing.JLabel();
        sl10 = new javax.swing.JLabel();
        lblKho10 = new javax.swing.JLabel();
        pnel1 = new javax.swing.JPanel();
        hinh1 = new javax.swing.JLabel();
        ten1 = new javax.swing.JLabel();
        lblgia1 = new javax.swing.JLabel();
        gia1 = new javax.swing.JLabel();
        lblKho1 = new javax.swing.JLabel();
        sl1 = new javax.swing.JLabel();
        pnel4 = new javax.swing.JPanel();
        hinh4 = new javax.swing.JLabel();
        ten4 = new javax.swing.JLabel();
        lblgia4 = new javax.swing.JLabel();
        gia4 = new javax.swing.JLabel();
        sl4 = new javax.swing.JLabel();
        lblKho4 = new javax.swing.JLabel();
        pnel11 = new javax.swing.JPanel();
        hinh11 = new javax.swing.JLabel();
        ten11 = new javax.swing.JLabel();
        lblgia11 = new javax.swing.JLabel();
        gia11 = new javax.swing.JLabel();
        sl11 = new javax.swing.JLabel();
        lblKho11 = new javax.swing.JLabel();
        pnel2 = new javax.swing.JPanel();
        hinh2 = new javax.swing.JLabel();
        ten2 = new javax.swing.JLabel();
        lblgia2 = new javax.swing.JLabel();
        gia2 = new javax.swing.JLabel();
        sl2 = new javax.swing.JLabel();
        lblKho2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLastDS = new javax.swing.JButton();
        btnPrevDS = new javax.swing.JButton();
        btnNextDS = new javax.swing.JButton();
        btnFirstDS = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnel6.setBackground(new java.awt.Color(255, 255, 255));
        pnel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten6.setText("CUSHION EDP LAMÉ COLLECTOR");

        lblgia6.setText("Giá:");

        gia6.setForeground(new java.awt.Color(255, 51, 51));
        gia6.setText("1960000");

        sl6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl6.setText("20");

        lblKho6.setText("Kho còn:");

        javax.swing.GroupLayout pnel6Layout = new javax.swing.GroupLayout(pnel6);
        pnel6.setLayout(pnel6Layout);
        pnel6Layout.setHorizontalGroup(
            pnel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel6Layout.createSequentialGroup()
                .addGroup(pnel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel6Layout.createSequentialGroup()
                        .addComponent(lblgia6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnel6Layout.createSequentialGroup()
                        .addComponent(lblKho6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel6Layout.setVerticalGroup(
            pnel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia6)
                    .addComponent(gia6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho6)
                    .addComponent(sl6))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel8.setBackground(new java.awt.Color(255, 255, 255));
        pnel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten8.setText("PHẤN PHỦ SOUFFLE DECLAT");

        lblgia8.setText("Giá:");

        gia8.setForeground(new java.awt.Color(255, 51, 51));
        gia8.setText("1900000");

        sl8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl8.setText("100");

        lblKho8.setText("Kho còn:");

        javax.swing.GroupLayout pnel8Layout = new javax.swing.GroupLayout(pnel8);
        pnel8.setLayout(pnel8Layout);
        pnel8Layout.setHorizontalGroup(
            pnel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel8Layout.createSequentialGroup()
                .addGroup(pnel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel8Layout.createSequentialGroup()
                        .addComponent(lblgia8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnel8Layout.createSequentialGroup()
                        .addComponent(lblKho8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel8Layout.setVerticalGroup(
            pnel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia8)
                    .addComponent(gia8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho8)
                    .addComponent(sl8))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel5.setBackground(new java.awt.Color(255, 255, 255));
        pnel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten5.setText("BẢNG MẮT COUTURE COLOR CLUTCH");

        lblgia5.setText("Giá:");

        gia5.setForeground(new java.awt.Color(255, 51, 51));
        gia5.setText("3800000");

        sl5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl5.setText("24");

        lblKho5.setText("Kho còn:");

        javax.swing.GroupLayout pnel5Layout = new javax.swing.GroupLayout(pnel5);
        pnel5.setLayout(pnel5Layout);
        pnel5Layout.setHorizontalGroup(
            pnel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel5Layout.createSequentialGroup()
                .addGroup(pnel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel5Layout.createSequentialGroup()
                        .addComponent(lblgia5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnel5Layout.createSequentialGroup()
                        .addComponent(lblKho5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel5Layout.setVerticalGroup(
            pnel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia5)
                    .addComponent(gia5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho5)
                    .addComponent(sl5))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel9.setBackground(new java.awt.Color(255, 255, 255));
        pnel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten9.setText("KEM CHỐNG NẮNG PURE SHOTS AIRTHIN UV DEFENDER");

        lblgia9.setText("Giá:");

        gia9.setForeground(new java.awt.Color(255, 51, 51));
        gia9.setText("1800000");

        sl9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl9.setText("100");

        lblKho9.setText("Kho còn:");

        javax.swing.GroupLayout pnel9Layout = new javax.swing.GroupLayout(pnel9);
        pnel9.setLayout(pnel9Layout);
        pnel9Layout.setHorizontalGroup(
            pnel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel9Layout.createSequentialGroup()
                .addGroup(pnel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel9Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel9Layout.createSequentialGroup()
                        .addComponent(lblgia9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnel9Layout.createSequentialGroup()
                        .addComponent(lblKho9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel9Layout.setVerticalGroup(
            pnel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia9)
                    .addComponent(gia9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho9)
                    .addComponent(sl9))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel12.setBackground(new java.awt.Color(255, 255, 255));
        pnel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten12.setText("Tinh chất chống lão hóa, tái tạo da The Ordinary “Buffet”");

        lblgia12.setText("Giá:");

        gia12.setForeground(new java.awt.Color(255, 51, 51));
        gia12.setText("810000");

        sl12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl12.setText("10");

        lblKho12.setText("Kho còn:");

        javax.swing.GroupLayout pnel12Layout = new javax.swing.GroupLayout(pnel12);
        pnel12.setLayout(pnel12Layout);
        pnel12Layout.setHorizontalGroup(
            pnel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel12Layout.createSequentialGroup()
                .addGroup(pnel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel12Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel12Layout.createSequentialGroup()
                        .addComponent(lblgia12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnel12Layout.createSequentialGroup()
                        .addComponent(lblKho12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel12Layout.setVerticalGroup(
            pnel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia12)
                    .addComponent(gia12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho12)
                    .addComponent(sl12))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel3.setBackground(new java.awt.Color(255, 255, 255));
        pnel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten3.setText("SON KEM LÌ TATOUAGE COUTURE VELVET CREAM");

        lblgia3.setText("Giá:");

        gia3.setForeground(new java.awt.Color(255, 51, 51));
        gia3.setText("1200000");

        sl3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl3.setText("Hết");

        lblKho3.setText("Kho còn:");

        javax.swing.GroupLayout pnel3Layout = new javax.swing.GroupLayout(pnel3);
        pnel3.setLayout(pnel3Layout);
        pnel3Layout.setHorizontalGroup(
            pnel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel3Layout.createSequentialGroup()
                .addGroup(pnel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel3Layout.createSequentialGroup()
                        .addComponent(lblgia3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnel3Layout.createSequentialGroup()
                        .addComponent(lblKho3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel3Layout.setVerticalGroup(
            pnel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia3)
                    .addComponent(gia3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho3)
                    .addComponent(sl3))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel7.setBackground(new java.awt.Color(255, 255, 255));
        pnel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten7.setText("MASCARA MVEFC WATERPROOF");

        lblgia7.setText("Giá:");

        gia7.setForeground(new java.awt.Color(255, 51, 51));
        gia7.setText("1400000");

        sl7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl7.setText("60");

        lblKho7.setText("Kho còn:");

        javax.swing.GroupLayout pnel7Layout = new javax.swing.GroupLayout(pnel7);
        pnel7.setLayout(pnel7Layout);
        pnel7Layout.setHorizontalGroup(
            pnel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel7Layout.createSequentialGroup()
                .addGroup(pnel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel7Layout.createSequentialGroup()
                        .addComponent(lblgia7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnel7Layout.createSequentialGroup()
                        .addComponent(lblKho7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel7Layout.setVerticalGroup(
            pnel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia7)
                    .addComponent(gia7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho7)
                    .addComponent(sl7))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel10.setBackground(new java.awt.Color(255, 255, 255));
        pnel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten10.setText("KEM DƯỠNG ẨM PURE SHOTS PERFECT PLUMPER");

        lblgia10.setText("Giá:");

        gia10.setForeground(new java.awt.Color(255, 51, 51));
        gia10.setText("4000000");

        sl10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl10.setText("40");

        lblKho10.setText("Kho còn:");

        javax.swing.GroupLayout pnel10Layout = new javax.swing.GroupLayout(pnel10);
        pnel10.setLayout(pnel10Layout);
        pnel10Layout.setHorizontalGroup(
            pnel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel10Layout.createSequentialGroup()
                .addGroup(pnel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel10Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel10Layout.createSequentialGroup()
                        .addComponent(lblgia10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnel10Layout.createSequentialGroup()
                        .addComponent(lblKho10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel10Layout.setVerticalGroup(
            pnel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia10)
                    .addComponent(gia10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho10)
                    .addComponent(sl10))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel1.setBackground(new java.awt.Color(255, 255, 255));
        pnel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SON MÔI ROUGE PUR COUTURE THE SLIM VELVET RADICAL.jpg"))); // NOI18N
        hinh1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten1.setText("SP1");

        lblgia1.setText("Giá:");

        gia1.setForeground(new java.awt.Color(255, 51, 51));
        gia1.setText("1200000");

        lblKho1.setText("Kho còn:");

        sl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl1.setText("Hết");

        javax.swing.GroupLayout pnel1Layout = new javax.swing.GroupLayout(pnel1);
        pnel1.setLayout(pnel1Layout);
        pnel1Layout.setHorizontalGroup(
            pnel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ten1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgia1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnel1Layout.createSequentialGroup()
                        .addComponent(sl1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addContainerGap())
            .addGroup(pnel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(hinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnel1Layout.setVerticalGroup(
            pnel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ten1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia1)
                    .addComponent(gia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho1)
                    .addComponent(sl1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel4.setBackground(new java.awt.Color(255, 255, 255));
        pnel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten4.setText("SON THỎI SATIN LÌ THE BOLD");

        lblgia4.setText("Giá:");

        gia4.setForeground(new java.awt.Color(255, 51, 51));
        gia4.setText("1200000");

        sl4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl4.setText("20");

        lblKho4.setText("Kho còn:");

        javax.swing.GroupLayout pnel4Layout = new javax.swing.GroupLayout(pnel4);
        pnel4.setLayout(pnel4Layout);
        pnel4Layout.setHorizontalGroup(
            pnel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel4Layout.createSequentialGroup()
                .addGroup(pnel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel4Layout.createSequentialGroup()
                        .addComponent(lblgia4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnel4Layout.createSequentialGroup()
                        .addComponent(lblKho4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel4Layout.setVerticalGroup(
            pnel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia4)
                    .addComponent(gia4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho4)
                    .addComponent(sl4))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel11.setBackground(new java.awt.Color(255, 255, 255));
        pnel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh11.setBackground(new java.awt.Color(255, 255, 255));
        hinh11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten11.setText("PURE SHOTS LINES AWAY SERUM");

        lblgia11.setText("Giá:");

        gia11.setForeground(new java.awt.Color(255, 51, 51));
        gia11.setText("3280000");

        sl11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl11.setText("30");

        lblKho11.setText("Kho còn:");

        javax.swing.GroupLayout pnel11Layout = new javax.swing.GroupLayout(pnel11);
        pnel11.setLayout(pnel11Layout);
        pnel11Layout.setHorizontalGroup(
            pnel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel11Layout.createSequentialGroup()
                .addGroup(pnel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel11Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel11Layout.createSequentialGroup()
                        .addComponent(lblgia11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnel11Layout.createSequentialGroup()
                        .addComponent(lblKho11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel11Layout.setVerticalGroup(
            pnel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia11)
                    .addComponent(gia11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho11)
                    .addComponent(sl11))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnel2.setBackground(new java.awt.Color(255, 255, 255));
        pnel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        hinh2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));

        ten2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ten2.setText("SON MÔI ROUGE PUR COUTURE THE SLIM VELVET RADICAL");

        lblgia2.setText("Giá:");

        gia2.setForeground(new java.awt.Color(255, 51, 51));
        gia2.setText("1200000");

        sl2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sl2.setText("20");

        lblKho2.setText("Kho còn:");

        javax.swing.GroupLayout pnel2Layout = new javax.swing.GroupLayout(pnel2);
        pnel2.setLayout(pnel2Layout);
        pnel2Layout.setHorizontalGroup(
            pnel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel2Layout.createSequentialGroup()
                .addGroup(pnel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ten2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnel2Layout.createSequentialGroup()
                        .addComponent(lblgia2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnel2Layout.createSequentialGroup()
                        .addComponent(lblKho2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sl2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnel2Layout.setVerticalGroup(
            pnel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ten2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgia2)
                    .addComponent(gia2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKho2)
                    .addComponent(sl2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnLastDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/last.png"))); // NOI18N
        btnLastDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastDSActionPerformed(evt);
            }
        });

        btnPrevDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prev.png"))); // NOI18N
        btnPrevDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevDSActionPerformed(evt);
            }
        });

        btnNextDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        btnNextDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextDSActionPerformed(evt);
            }
        });

        btnFirstDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/first.png"))); // NOI18N
        btnFirstDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstDSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFirstDS)
                .addGap(18, 18, 18)
                .addComponent(btnNextDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrevDS)
                .addGap(18, 18, 18)
                .addComponent(btnLastDS)
                .addGap(500, 500, 500))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFirstDS)
                    .addComponent(btnNextDS)
                    .addComponent(btnPrevDS)
                    .addComponent(btnLastDS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblDongHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDongHo.setText("00:00:00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Hệ thống");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Trợ giúp");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void FillSP(SanPham sp, JPanel pnel, JLabel hinh, JLabel ten, JLabel gia, JLabel sl, JLabel lblGia, JLabel lblKho) {
        try {
            setHinhAnh(sp.getHinh(), hinh);
            hinh.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204), 1));
            pnel.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204), 1));
            //pnel.setVisible(true);
            ten.setText(sp.getTensp());
            gia.setText(sp.getGia() + "");
            if (sp.getSoLuong() < 10 && sp.getSoLuong() > 0) {
                sl.setForeground(Color.red);
            } else if (sp.getSoLuong() == 0) {
                sl.setForeground(Color.red);
                sl.setText("Hết");
            } else {
                sl.setForeground(Color.black);
            }
            sl.setText(sp.getSoLuong() + "");
            lblGia.setText("Giá:");
            lblKho.setText("Kho còn:");
        } catch (Exception e) {
        }
    }
    
    public void clear(JPanel pnel, JLabel hinh, JLabel ten, JLabel gia, JLabel sl, JLabel lblGia, JLabel lblKho) {
        pnel.setBorder(null);
        pnel.setSize(160, 188);
        hinh.setIcon(null);
        hinh.setBorder(null);
        ten.setText(null);
        gia.setText(null);
        sl.setText(null);
        lblGia.setText(null);
        lblKho.setText(null);
    }
    
    public void clearPage() {
        clear(pnel1, hinh1, ten1, gia1, sl1, lblgia1, lblKho1);
        clear(pnel2, hinh2, ten2, gia2, sl2, lblgia2, lblKho2);
        clear(pnel3, hinh3, ten3, gia3, sl3, lblgia3, lblKho3);
        clear(pnel4, hinh4, ten4, gia4, sl4, lblgia4, lblKho4);
        clear(pnel5, hinh5, ten5, gia5, sl5, lblgia5, lblKho5);
        clear(pnel6, hinh6, ten6, gia6, sl6, lblgia6, lblKho6);
        clear(pnel7, hinh7, ten7, gia7, sl7, lblgia7, lblKho7);
        clear(pnel8, hinh8, ten8, gia8, sl8, lblgia8, lblKho8);
        clear(pnel9, hinh9, ten9, gia9, sl9, lblgia9, lblKho9);
        clear(pnel10, hinh10, ten10, gia10, sl10, lblgia10, lblKho10);
        clear(pnel11, hinh11, ten11, gia11, sl11, lblgia11, lblKho11);
        clear(pnel12, hinh12, ten12, gia12, sl12, lblgia12, lblKho12);
//        pnel1.setVisible(false);
//        pnel2.setVisible(false);
//        pnel3.setVisible(false);
//        pnel4.setVisible(false);
//        pnel5.setVisible(false);
//        pnel6.setVisible(false);
//        pnel7.setVisible(false);
//        pnel8.setVisible(false);
//        pnel9.setVisible(false);
//        pnel10.setVisible(false);
//        pnel11.setVisible(false);
//        pnel12.setVisible(false);
    }
    
    public void setHinhAnh(String path, JLabel hinh) {
        ImageIcon img = new ImageIcon(getClass().getResource("/img/" + path));
        Image image = img.getImage();
        Image image2 = image.getScaledInstance(111, 93,
                Image.SCALE_SMOOTH);
        hinh.setIcon(new ImageIcon(image2));
    }
    
    public void FillPageSP() {
        int vitri = 0;
        list = dao.selectAll();
        for (SanPham sp : list) {
            //System.out.println(vitri);
            vitri++;
            if (vitri == this.page * 12 - 11) {
                FillSP(sp, pnel1, hinh1, ten1, gia1, sl1, lblgia1, lblKho1);
            } else if (vitri == this.page * 12 - 10) {
                FillSP(sp, pnel2, hinh2, ten2, gia2, sl2, lblgia2, lblKho2);
            } else if (vitri == this.page * 12 - 9) {
                FillSP(sp, pnel3, hinh3, ten3, gia3, sl3, lblgia3, lblKho3);
            } else if (vitri == this.page * 12 - 8) {
                FillSP(sp, pnel4, hinh4, ten4, gia4, sl4, lblgia4, lblKho4);
            } else if (vitri == this.page * 12 - 7) {
                FillSP(sp, pnel5, hinh5, ten5, gia5, sl5, lblgia5, lblKho5);
            } else if (vitri == this.page * 12 - 6) {
                FillSP(sp, pnel6, hinh6, ten6, gia6, sl6, lblgia6, lblKho6);
            } else if (vitri == this.page * 12 - 5) {
                FillSP(sp, pnel7, hinh7, ten7, gia7, sl7, lblgia7, lblKho7);
            } else if (vitri == this.page * 12 - 4) {
                FillSP(sp, pnel8, hinh8, ten8, gia8, sl8, lblgia8, lblKho8);
            } else if (vitri == this.page * 12 - 3) {
                FillSP(sp, pnel9, hinh9, ten9, gia9, sl9, lblgia9, lblKho9);
            } else if (vitri == this.page * 12 - 2) {
                FillSP(sp, pnel10, hinh10, ten10, gia10, sl10, lblgia10, lblKho10);
            } else if (vitri == this.page * 12 - 1) {
                FillSP(sp, pnel11, hinh11, ten11, gia11, sl11, lblgia11, lblKho11);
            } else if (vitri == this.page * 12) {
                FillSP(sp, pnel12, hinh12, ten12, gia12, sl12, lblgia12, lblKho12);
            }
        }
    }
    
    public void getForm(String ten) {
        SanPham sp = dao.selectByKeyword(ten);
        FillSP(sp, pnel1, hinh1, ten1, gia1, sl1, lblgia1, lblKho1);
    }
    
    @Override
    public void run() {
        while (true) {
            try {
                Date now = new Date();
                SimpleDateFormat fomater = new SimpleDateFormat("hh:mm:ss");
                lblDongHo.setText(fomater.format(now));
                Thread.sleep(1000);
            } catch (Exception e) {
                break;
            }
        }
    }
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnFirstDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstDSActionPerformed
        clearPage();
        this.page = 1;
        this.FillPageSP();
    }//GEN-LAST:event_btnFirstDSActionPerformed

    private void btnNextDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextDSActionPerformed
        clearPage();
        this.page++;
        int maxPage = (int) Math.floor(list.size() / 8);
        if (this.page > maxPage) {
            this.page = maxPage;
            System.out.println("maxpage" + maxPage);
        }
        this.FillPageSP();
    }//GEN-LAST:event_btnNextDSActionPerformed

    private void btnPrevDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevDSActionPerformed
        clearPage();
        this.page--;
        System.out.println("prevp" + page);
        if (this.page < 1) {
            this.page = 1;
        }
        this.FillPageSP();
    }//GEN-LAST:event_btnPrevDSActionPerformed

    private void btnLastDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastDSActionPerformed
        clearPage();
        int maxPage = (int) Math.floor(list.size() / 8);
        System.out.println("size" + list.size());
        System.out.println("max" + maxPage);
        this.page = maxPage;
        this.FillPageSP();
    }//GEN-LAST:event_btnLastDSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearPage();
        this.getForm(txtSearch.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Thread clock = new Thread(this);
        clock.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstDS;
    private javax.swing.JButton btnLastDS;
    private javax.swing.JButton btnNextDS;
    private javax.swing.JButton btnPrevDS;
    private javax.swing.JLabel gia1;
    private javax.swing.JLabel gia10;
    private javax.swing.JLabel gia11;
    private javax.swing.JLabel gia12;
    private javax.swing.JLabel gia2;
    private javax.swing.JLabel gia3;
    private javax.swing.JLabel gia4;
    private javax.swing.JLabel gia5;
    private javax.swing.JLabel gia6;
    private javax.swing.JLabel gia7;
    private javax.swing.JLabel gia8;
    private javax.swing.JLabel gia9;
    private javax.swing.JLabel hinh1;
    private javax.swing.JLabel hinh10;
    private javax.swing.JLabel hinh11;
    private javax.swing.JLabel hinh12;
    private javax.swing.JLabel hinh2;
    private javax.swing.JLabel hinh3;
    private javax.swing.JLabel hinh4;
    private javax.swing.JLabel hinh5;
    private javax.swing.JLabel hinh6;
    private javax.swing.JLabel hinh7;
    private javax.swing.JLabel hinh8;
    private javax.swing.JLabel hinh9;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblKho1;
    private javax.swing.JLabel lblKho10;
    private javax.swing.JLabel lblKho11;
    private javax.swing.JLabel lblKho12;
    private javax.swing.JLabel lblKho2;
    private javax.swing.JLabel lblKho3;
    private javax.swing.JLabel lblKho4;
    private javax.swing.JLabel lblKho5;
    private javax.swing.JLabel lblKho6;
    private javax.swing.JLabel lblKho7;
    private javax.swing.JLabel lblKho8;
    private javax.swing.JLabel lblKho9;
    private javax.swing.JLabel lblgia1;
    private javax.swing.JLabel lblgia10;
    private javax.swing.JLabel lblgia11;
    private javax.swing.JLabel lblgia12;
    private javax.swing.JLabel lblgia2;
    private javax.swing.JLabel lblgia3;
    private javax.swing.JLabel lblgia4;
    private javax.swing.JLabel lblgia5;
    private javax.swing.JLabel lblgia6;
    private javax.swing.JLabel lblgia7;
    private javax.swing.JLabel lblgia8;
    private javax.swing.JLabel lblgia9;
    private javax.swing.JPanel pnel1;
    private javax.swing.JPanel pnel10;
    private javax.swing.JPanel pnel11;
    private javax.swing.JPanel pnel12;
    private javax.swing.JPanel pnel2;
    private javax.swing.JPanel pnel3;
    private javax.swing.JPanel pnel4;
    private javax.swing.JPanel pnel5;
    private javax.swing.JPanel pnel6;
    private javax.swing.JPanel pnel7;
    private javax.swing.JPanel pnel8;
    private javax.swing.JPanel pnel9;
    private javax.swing.JLabel sl1;
    private javax.swing.JLabel sl10;
    private javax.swing.JLabel sl11;
    private javax.swing.JLabel sl12;
    private javax.swing.JLabel sl2;
    private javax.swing.JLabel sl3;
    private javax.swing.JLabel sl4;
    private javax.swing.JLabel sl5;
    private javax.swing.JLabel sl6;
    private javax.swing.JLabel sl7;
    private javax.swing.JLabel sl8;
    private javax.swing.JLabel sl9;
    private javax.swing.JLabel ten1;
    private javax.swing.JLabel ten10;
    private javax.swing.JLabel ten11;
    private javax.swing.JLabel ten12;
    private javax.swing.JLabel ten2;
    private javax.swing.JLabel ten3;
    private javax.swing.JLabel ten4;
    private javax.swing.JLabel ten5;
    private javax.swing.JLabel ten6;
    private javax.swing.JLabel ten7;
    private javax.swing.JLabel ten8;
    private javax.swing.JLabel ten9;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
