/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlsmp.MainInterface;

import qlsmp.MainInterface.*;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;

/**
 *
 * @author My Laptop
 */
public class CardMain extends javax.swing.JPanel {

    private Color color1;
    private Color color2;
    private String ten;

    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }

    public String getTen() {
        return ten;
    }

    public void setTen(String ten) {
        this.ten = ten;
    }

    public JLabel getLbten() {
        return lbten;
    }

    public void setLbten(JLabel lbten) {
        this.lbten = lbten;
    }

    /**
     * Creates new form CartMain
     */
    public CardMain() {
        initComponents();
        setOpaque(false);
        color1 = Color.BLACK;
        color2 = Color.white;
        ten = "Hàng nè";
    }

    @Override
    public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();
        GradientPaint gradient = new GradientPaint(0, 0, color1, 0, height, color2);

        g2d.setPaint(gradient);
        //g2d.fillRoundRect(0, 0, height, width, 15, 15);
       // g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
       // g2d.setColor(Color.WHITE);
       // g2d.fillOval (width-(height/2),10,height,height);
       // g2d.fillOval (width-(height/2)-20,height/2+20,height,height);
        g2d.fillRect(0, 0, width, height);
        
        super.paint(g);
        lbten.setText(ten);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbten = new javax.swing.JLabel();

        lbten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbten.setForeground(new java.awt.Color(255, 255, 255));
        lbten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbten.setText("Hàng hóa");
        lbten.setToolTipText("");
        lbten.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbten.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbten.setInheritsPopupMenu(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbten, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbten)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbten;
    // End of variables declaration//GEN-END:variables
}
